stages:
  - release

release:module:
  stage: release
  image: node:12
  script:
    - npx -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/gitlab -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release --
  only:
    refs:
      - master
